# Decision tree Regression

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('F:\Machine Learning\Task\WorldPopulation.csv')
df.head()

Year  Population  ChangePerc  NetChange  Density       Urban  UrbanPerc
0  2020  7794798739        1.05   81330639       52  4378993944         56
1  2019  7713468100        1.08   82377060       52  4299438618         56
2  2018  7631091040        1.10   83232115       51  4219817318         55
3  2017  7547858925        1.12   83836876       51  4140188594         55
4  2016  7464022049        1.14   84224910       50  4060652683         54

In [3]:
df.tail()

Year  Population  ChangePerc  NetChange  Density      Urban  UrbanPerc
65  1955  2773019936        1.77   48173195       19  877008842         32
66  1954  2724846741        1.76   47237781       18  850179106         31
67  1953  2677608960        1.78   46747398       18  824289989         31
68  1952  2630861562        1.81   46827301       18  799282533         30
69  1951  2584034261        1.88   47603112       17  775067697         30

In [4]:
df.describe()

Year    Population  ChangePerc     NetChange    Density  \
count    70.000000  7.000000e+01   70.000000  7.000000e+01  70.000000   
mean   1985.500000  5.002010e+09    1.616429  7.511954e+07  33.557143   
std      20.351085  1.594877e+09    0.321288  1.256972e+07  10.723989   
min    1951.000000  2.584034e+09    1.050000  4.674740e+07  17.000000   
25%    1968.250000  3.570120e+09    1.262500  7.314225e+07  24.000000   
50%    1985.500000  4.915745e+09    1.770000  7.942852e+07  33.000000   
75%    2002.750000  6.361332e+09    1.847500  8.356683e+07  42.750000   
max    2020.000000  7.794799e+09    2.090000  9.290386e+07  52.000000   

              Urban  UrbanPerc  
count  7.000000e+01  70.000000  
mean   2.226815e+09  42.200000  
std    1.070191e+09   7.447595  
min    7.750677e+08  30.000000  
25%    1.294408e+09  36.000000  
50%    2.035272e+09  41.500000  
75%    3.054260e+09  48.000000  
max    4.378994e+09  56.000000

In [5]:
df.isnull().sum()

Year          0
Population    0
ChangePerc    0
NetChange     0
Density       0
Urban         0
UrbanPerc     0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Year        70 non-null     int64  
 1   Population  70 non-null     int64  
 2   ChangePerc  70 non-null     float64
 3   NetChange   70 non-null     int64  
 4   Density     70 non-null     int64  
 5   Urban       70 non-null     int64  
 6   UrbanPerc   70 non-null     int64  
dtypes: float64(1), int64(6)
memory usage: 4.0 KB


In [9]:
x = df.iloc[:,:3]
y = df.iloc[:,4]

In [11]:
x.shape,y.shape

((70, 3), (70,))

### train test split

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 99)
print('X_train Shape -',x_train.shape)
print('X_test Shape -',x_test.shape)
print('Y_train Shape -',y_train.shape)
print('Y_test Shape -',y_test.shape)

X_train Shape - (56, 3)
X_test Shape - (14, 3)
Y_train Shape - (56,)
Y_test Shape - (14,)


### Import Decision Tree Regression

In [22]:
from sklearn.tree import DecisionTreeRegressor
dtr = DecisionTreeRegressor(criterion='mae',random_state = 95)

In [23]:
dtr.fit(x,y)

DecisionTreeRegressor(criterion='mae', random_state=95)

### Prediction

In [25]:
y_pred = dtr.predict(x)
y_pred

array([52., 52., 51., 51., 50., 50., 49., 48., 48., 47., 47., 46., 46.,
       45., 44., 44., 43., 43., 42., 42., 41., 41., 40., 40., 39., 39.,
       38., 37., 37., 36., 36., 35., 35., 34., 33., 33., 32., 32., 31.,
       30., 30., 29., 29., 28., 28., 27., 27., 26., 26., 25., 25., 24.,
       24., 23., 23., 22., 22., 22., 21., 21., 20., 20., 20., 19., 19.,
       19., 18., 18., 18., 17.])

In [26]:
from sklearn.metrics import r2_score,accuracy_score

In [28]:
r2_score(y,y_pred)*100

100.0

In [31]:
dtr.predict([[2017,7547858925,1.12]])

array([51.])

In [32]:
df.head()

Year  Population  ChangePerc  NetChange  Density       Urban  UrbanPerc
0  2020  7794798739        1.05   81330639       52  4378993944         56
1  2019  7713468100        1.08   82377060       52  4299438618         56
2  2018  7631091040        1.10   83232115       51  4219817318         55
3  2017  7547858925        1.12   83836876       51  4140188594         55
4  2016  7464022049        1.14   84224910       50  4060652683         54

In [35]:
dtr.predict([[1955,2773019936,1.77]])

array([19.])

In [33]:
df.tail()

Year  Population  ChangePerc  NetChange  Density      Urban  UrbanPerc
65  1955  2773019936        1.77   48173195       19  877008842         32
66  1954  2724846741        1.76   47237781       18  850179106         31
67  1953  2677608960        1.78   46747398       18  824289989         31
68  1952  2630861562        1.81   46827301       18  799282533         30
69  1951  2584034261        1.88   47603112       17  775067697         30